### ISSUE TITLE
Some way to keep borders intact

### ISSUE THREAD

**Issue by DiTayal** [cheind/py-thin-plate-spline#4]
Sir, is there some way in which we can cover up the black portion formed in image interpolation, i.e the boundary of image should not be disturbed (How to eliminate the black part)
<img width="326" alt="Capture" src="https://user-images.githubusercontent.com/43693628/87423356-c7eccb80-c5f7-11ea-9c79-9be33e73e74b.PNG">

**Comment by cheind** [comment]
Hey, you might want to
 - additional points to the border. and modify only the inner points, or
 - crop the image such that no black border is visible.

**Comment by DiTayal** [comment]
Thank you Sir, for these alternatives.

Sir, I have one more question that can we use this code in polar coordinate system?
Some thoughts would be very helpful.
Thank you

**Comment by cheind** [comment]
I'm not sure what you are trying to achieve. TPS will take any coordinates
you feed him, whether you later interpret them as Cartesian or polar.
However, if the interpolation is meaningful for polar - I don't know.

Best,
Christoph

**Comment by DiTayal** [comment]
Sir,Thanks a lot for your replys.
Indeed got worthy points.
